name: Fetch Assets

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:
  repository_dispatch:

jobs:
  fetch-assets:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1
      - name: Install dependencies
        run: npm install
      - name: Fetch RSS Feeds
        run: npm run fetch-assets
      - name: Commit files
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          STATUS=$(git status -s)
          if [ -n "$STATUS" ]; then
            git commit -m "Update rss.json `date +'%Y-%m-%d %H:%M:%S'`" -a
            git push origin main
          fi
